### ISSUE TITLE
Use with the mailgun api?

### ISSUE THREAD

**Issue by jamauro** [proper-software/mjml#1]
Would love to use this in my project but I'm using the mailgun api to send the email. Is it possible to get them working together?

**Comment by tomasz-nolberczak** [comment]
Hi @jamauro! Of course there could be a possible solution for that, but first I would like to know some more details about possible use. How are you using Mailgun API? Are you using some third-party library?

**Comment by jamauro** [comment]
I'm using `mailgun-js` to send emails

**Comment by johnwils** [comment]
Meteor added native Mailgun integration a couple months ago:

https://www.mailgun.com/blog/native-mailgun-integration-lets-meteor-apps-send-email/

This package should work out-of-the box with mailgun.

If you deploy to galaxy add your mailgun MAIL_URL to `settings.json`:

```
  "galaxy.meteor.com": {
    "env": {
      "MAIL_URL": "<mailgun_url_here>"
    }
  }
```

Send a test email locally by setting the MAIL_URL programatically in your Meteor server code:

```
Meteor.startup(() => {
  process.env.MAIL_URL = '<mailgun_url>'; (be careful this will send real emails)
});
```

Then send an email:

```
 Email.sendWithMjmlTemplate({
      showLogs: true,
      template: {
        name: 'emails/passwordReset.mjml', // MJML file template located in private/ directory
        params: {
          userEmail: 'some@email.com', // some variable to insert via handlebars
          url: 'some password reset url', // some variable to insert via handlebars
        },
      },
      from: 'support@email.com',
      to: 'some@email.com',
      subject: 'It works!',
    });
```

**Comment by tomasz-nolberczak** [comment]
@jamauro I think we can close that issue now - currently Meteor supports MailGun out of the box, so there are no need of any changes in the package.
