### ISSUE TITLE
ReferenceError: Can't find variable: Npm

### ISSUE THREAD

**Issue by johnwils** [proper-software/mjml#2]
In the web browser I'm getting an error: `ReferenceError: Can't find variable: Npm`

I think this package is meant for server only, but it is being installed in both client and server.

I believe the line in package.js:

```
api.mainModule("mjml.ts");
```

can be changed to

```
api.mainModule("mjml.ts", "server");
```

This may solve the issue and remove the warning in the browser.

BTW - thanks for writing this package I find it is really helpful and useful.

**Comment by tomasz-nolberczak** [comment]
Hi, thanks for creating a new issue. I am going to check what is happening.

What version of Meteor are you using?

**Comment by johnwils** [comment]
Hi,

I cloned your package and made some changes and it seems to work now and error is gone.

I’m using Meteor 1.12. I had to update the mjml dependencies to the latest version (i.e. typescript) and specify ‘server’ in the mjml package.

**Comment by tomasz-nolberczak** [comment]
Great! Thank you for your help out there. I think you can do a PR - then I will merged it with master 🙂

**Comment by tomasz-nolberczak** [comment]
@johnwils I spent some time today for doing a cleanup. I also fixed an issue you mentioned. Could you check if things are working correctly now within your project? 

Let me know, if the changes I made are fine for you.

I am going to publish the newest version to the Atmosphere soon. Now I am having some strange authorization issue from the Meteor's CLI. When that one will be fixed, I will do it immediately. 

PS: There are no tests yet - though I am going to add them in not too distant future, so I am sorry for that.
